import type { Metadata } from 'next'
import { Baloo_Chettan_2, Public_Sans } from 'next/font/google'
import './globals.css'

const balooChettan = Baloo_Chettan_2({
    subsets: ['latin'],
    variable: '--font-baloo-chettan',
})

const publicSans = Public_Sans({
    subsets: ['latin'],
    variable: '--font-public-sans',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${balooChettan.variable} ${publicSans.variable}`}>
                {children}
            </body>
        </html>
    )
}
